version: "3"

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward host port 8080 to container port 8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Forward host port 6379 to container port 6379
